EXCLUDE_VERSIONS=3.14.12.5
# Temporally removed to speed up
EXCLUDE_ARCHS += eldk

include ${EPICS_ENV_PATH}/module.Makefile

PROJECT=EthercatMC

AUTO_DEPENDENCIES = NO
USR_DEPENDENCIES += motor,6.9.5-ESS
USR_DEPENDENCIES += calc,3.6.1
#USR_DEPENDENCIES += seq,2.1.10


SOURCES = \
  EthercatMCApp/src/EthercatMCADS.cpp \
  EthercatMCApp/src/EthercatMCAxis.cpp \
  EthercatMCApp/src/EthercatMCController.cpp \
  EthercatMCApp/src/EthercatMCHelper.cpp \
  EthercatMCApp/src/EthercatMCIndexer.cpp \
  EthercatMCApp/src/EthercatMCIndexerAxis.cpp \



TEMPLATES = \
  EthercatMCApp/Db/EthercatMC.template \
  EthercatMCApp/Db/EthercatMCdebug.template \
  EthercatMCApp/Db/EthercatMChome.template \
  EthercatMCApp/Db/EthercatMCindexer.template \
  EthercatMCApp/Db/EthercatMCreadback.template \
  EthercatMCApp/Db/EthercatMCslit_soft.template \
  EthercatMCApp/Db/EthercatMCslit_hard.template \
  EthercatMCslitAvoidCollSoftlimits.template \


#MISCS = \
