move absolute position=24 max_velocity=10 acceleration=10 motorPosNow=96
move absolute position=48 max_velocity=2 acceleration=1.33333 motorPosNow=96
move absolute position=24 max_velocity=10 acceleration=10 motorPosNow=96
move absolute position=48 max_velocity=2 acceleration=1.33333 motorPosNow=96
move absolute position=24 max_velocity=10 acceleration=10 motorPosNow=96
move absolute position=48 max_velocity=2 acceleration=1.33333 motorPosNow=96
move absolute position=24 max_velocity=10 acceleration=10 motorPosNow=96
move absolute position=48 max_velocity=2 acceleration=1.33333 motorPosNow=96
