move relative delta=-72 max_velocity=10 acceleration=10 motorPosNow=96
move relative delta=-48 max_velocity=2 acceleration=1.33333 motorPosNow=96
move relative delta=-72 max_velocity=10 acceleration=10 motorPosNow=96
move relative delta=-48 max_velocity=2 acceleration=1.33333 motorPosNow=96
move relative delta=-36 max_velocity=10 acceleration=10 motorPosNow=96
move relative delta=-48 max_velocity=2 acceleration=1.33333 motorPosNow=96
move relative delta=-18 max_velocity=10 acceleration=10 motorPosNow=96
move relative delta=-48 max_velocity=2 acceleration=1.33333 motorPosNow=96
