move absolute position=24 max_velocity=10 acceleration=10 motorPosNow=72
move absolute position=48 max_velocity=2 acceleration=1.33333 motorPosNow=72
move absolute position=24 max_velocity=10 acceleration=10 motorPosNow=72
move absolute position=48 max_velocity=2 acceleration=1.33333 motorPosNow=72
move absolute position=40 max_velocity=10 acceleration=10 motorPosNow=72
move absolute position=48 max_velocity=2 acceleration=1.33333 motorPosNow=72
move absolute position=56 max_velocity=10 acceleration=10 motorPosNow=72
move absolute position=48 max_velocity=2 acceleration=1.33333 motorPosNow=72
