
GNERATEDOPIS: \
  ../motor-2.opi \
  ../motor-3.opi \
  ../motor-4.opi \
  ../motor-5.opi \
  ../motor-6.opi  \
  ../motor-4x3.opi \
  ../motor-4-2.opi \


#GNERATEDOPIS: \
#  ../motor-6-6-4.opi \



#
 ../motor-2.opi: Makefile genXY.sh motorx.end motorx.mid motorx.start
	./genXY.sh 2


../motor-3.opi: Makefile genXY.sh motorx.end motorx.mid motorx.start
	./genXY.sh 3


../motor-4.opi: Makefile genXY.sh motorx.end motorx.mid motorx.start
	./genXY.sh 4


../motor-5.opi: Makefile genXY.sh motorx.end motorx.mid motorx.start
	./genXY.sh 5


../motor-6.opi: Makefile genXY.sh motorx.end motorx.mid motorx.start
	./genXY.sh 6


../motor-4x3.opi: Makefile genXY.sh motorx.end motorx.mid motorx.start
	./genXY.sh 4 x 3


../motor-4-2.opi: Makefile genXY.sh motorx.end motorx.mid motorx.start
	./genXY.sh 4 2


#../motor-6-6-4.opi: Makefile genXY.sh motorx.end motorx.mid motorx.start
#	./genXY.sh 6 6 4



all: $(GNERATEDOPIS)

